### ISSUE TITLE
Please let us set the posting language(s)

### ISSUE THREAD

**Issue by kseistrup** [0xExal/bsky-bridge#2]
It seems the repo has been completely reset, and all issues erased — whether they have been imoplemented or not.

Should I re-submit the issue I opened a while ago about posting language, or doesn't it matter at this point?

**Comment by 0xExal** [comment]
Sure, you can re-submit your issue. I've started working on this feature, but there are still some problems.

**Comment by kseistrup** [comment]
Settings the posting language(s) seems to be rather straightforward:

https://docs.bsky.app/docs/advanced-guides/posts#setting-the-language

**Comment by kseistrup** [comment]
👍
