### ISSUE TITLE
Rate Limited due to session creation

### ISSUE THREAD

**Issue by ladewig** [0xExal/bsky-bridge#6]
Have run into an issue with getting rate limited when creating sessions.  Have seen a solution with the atproto library where they gave an example of dumping the session info to a text file and rereading that before creating a new session.

Looking in docs, however, it seems the better way to do it is to use the refreshtoken (refreshJwt) to refresh the session since that token has a longer life than the access token.

**Comment by 0xExal** [comment]
Hello,

It's an interesting suggestion. I will look into the implementation of the refresh token in the module.

**Comment by ladewig** [comment]
Thanks. This is the example from the atproto library: https://github.com/MarshalX/atproto/blob/main/examples/advanced_usage/session_reuse.py
